
// audio & FFT
#define DEFAULT_DEVICE_ID 1 // 15

#define PRINT_ALL_DEVICES
//#define OVEERRIDE_LATENCY x
#define OVERRIDE_SAMPLE_RATE 44100.0f

#define FRAMES_PER_BUFFER   128
#define FRAMES_PER_FFT      2048
#define FREQ_LOWER_BOUND    18.0f
#define FREQ_UPPER_BOUND    22000.0f

#define MAGNITUDE_FACTOR 1.35f


// raylib & gui
#define MAX_AMPLITUDE 1000

#define SCREEN_WIDTH    1920
#define SCREEN_HEIGHT   1080

// spectro to RGB
#define N_CHANNELS 4
#define ALGO Algo_FBDGM

// algos

// FBGM (frequency bin gradient mapping)

// HD = Hue Determination

#define FBGM_BASS_START                 FREQ_LOWER_BOUND
#define FBGM_BASS_G2_START              150.0f
#define FBGM_BASS_G2_END                250.0f

#define FBGM_MIDS_G1_START              250.0f
#define FBGM_MIDS_G1_END                350.0f
#define FBGM_MIDS_G2_START              4250.0f
#define FBGM_MIDS_G2_END                4750.0f

#define FBGM_MIDS_HD_G1_START           250.0f
#define FBGM_MIDS_HD_G1_END             300.0f
#define FBGM_MIDS_HD_END                4500.0f


#define FBGM_HIGHS_G1_START             4250.0f
#define FBGM_HIGHS_G1_END               4750.0f
#define FBGM_HIGHS_END                  FREQ_UPPER_BOUND

#define FBGM_HIGHS_HD_START             4500.0f
#define FBGM_HIGHS_HD_END               FREQ_UPPER_BOUND

#define FBGM_BASS_FACTOR                10.0f
#define FBGM_MIDS_FACTOR                30.0f
#define FBGM_HIGHS_FACTOR               60.0f

#define FBGM_MIDS_FLAOT_OVERFLOW_FACTOR 100.0f
#define FBGM_HIGHS_FLOAT_OVERFLOW_FACTOR 30.0f

//SFBGM (spiked frequency bin gradient mapping), a derivative of FBGM

#define SFBGM_BASS_SPIKE_DECAY_FACTOR         20.0f // higher = faster decay. INF = immediate decay, 0 = no decay
#define SFBGM_MIDS_SPIKE_DECAY_FACTOR         18.0f
#define SFBGM_HIGHS_SPIKE_DECAY_FACTOR        17.0f

// FBDGM (frequency bin division gradient mapping)
#define FBDGM_BASS_START FREQ_LOWER_BOUND
#define FBDGM_BASS_END 200.0f

#define FBDGM_MIDS_D1 FBDGM_BASS_END
#define FBDGM_MIDS_D2 1300.0f
#define FBDGM_MIDS_D3 4500.0f

#define FBDGM_HIGHS_D1 5500.0f
#define FBDGM_HIGHS_D2 12000.0f
#define FBDGM_HIGHS_D3 22000.0f


#define FBDGM_MIDS_D1_IN_LEN 0.0f
#define FBDGM_MIDS_D1_OUT_LEN (FBDGM_MIDS_D2 - FBDGM_MIDS_D1)
#define FBDGM_MIDS_D2_IN_LEN FBDGM_MIDS_D1_OUT_LEN
#define FBDGM_MIDS_D2_OUT_LEN (FBDGM_MIDS_D3 - FBDGM_MIDS_D2)
#define FBDGM_MIDS_D3_IN_LEN FBDGM_MIDS_D2_OUT_LEN
#define FBDGM_MIDS_D3_OUT_LEN (FBDGM_HIGHS_D1 - FBDGM_MIDS_D3)

#define FBDGM_HIGHS_D1_IN_LEN FBDGM_MIDS_D3_OUT_LEN
#define FBDGM_HIGHS_D1_OUT_LEN (FBDGM_HIGHS_D2 - FBDGM_HIGHS_D1)
#define FBDGM_HIGHS_D2_IN_LEN FBDGM_HIGHS_D1_OUT_LEN
#define FBDGM_HIGHS_D2_OUT_LEN (FBDGM_HIGHS_D3 - FBDGM_HIGHS_D2)
#define FBDGM_HIGHS_D3_IN_LEN FBDGM_HIGHS_D2_OUT_LEN
#define FBDFM_HIGHS_D3_OUT_LEN 0.0f



#define FBDGM_MIDS_D1_BASE_FACTOR 30.0f
#define FBDGM_MIDS_D2_BASE_FACTOR FBDGM_MIDS_D1_BASE_FACTOR
#define FBDGM_MIDS_D3_BASE_FACTOR FBDGM_MIDS_D1_BASE_FACTOR

#define FBDGM_HIGHS_D1_BASE_FACTOR 20.0f
#define FBDGM_HIGHS_D2_BASE_FACTOR FBDGM_HIGHS_D1_BASE_FACTOR
#define FBDGM_HIGHS_D3_BASE_FACTOR FBDGM_HIGHS_D1_BASE_FACTOR


#define FBDGM_BASS_FACTOR 13.0f

#define FBDGM_MIDS_D1_FACTOR (FBDGM_MIDS_D1_BASE_FACTOR / 2.0f)
#define FBDGM_MIDS_D2_FACTOR FBDGM_MIDS_D2_BASE_FACTOR
#define FBDGM_MIDS_D3_FACTOR FBDGM_MIDS_D3_BASE_FACTOR

#define FBDGM_HIGHS_D1_FACTOR FBDGM_HIGHS_D1_BASE_FACTOR
#define FBDGM_HIGHS_D2_FACTOR FBDGM_HIGHS_D2_BASE_FACTOR
#define FBDGM_HIGHS_D3_FACTOR (FBDGM_HIGHS_D3_BASE_FACTOR / 2.0f)
